import type { Metadata } from "next";
import localFont from "next/font/local";
import Gnb from "@/components/Gnb";
import "./globals.css";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.ttf",
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className} pt-[60px]`}>
        <Gnb />
        {children}
      </body>
    </html>
  );
}
